[package]
name = "locksmith"
version = "0.1.0"
edition = "2024"

[features]
default = ["rpgpie"]
rpgpie = [
	"dep:card-backend-pcsc",
	"dep:openpgp-card",
	"dep:openpgp-card-rpgp",
	"dep:pgp",
	"dep:rpgpie",
	"dep:card-backend",
]

[dependencies]
# rpgpie
pgp = { version = "0.19.0", optional = true }
rpgpie = { version = "0.9.0", optional = true }
openpgp-card = { version = "0.6.0", optional = true }
card-backend = { version = "0.2.0", optional = true }
card-backend-pcsc = { version = "0.5.1", optional = true }
openpgp-card-rpgp = { version = "0.7.0", optional = true }

cfg-if = "1.0.4"
structstruck = "0.5.1"
dterror = "0.1.0"
thiserror = "2.0.18"

serde = "1.0.228"
serde_json = "1.0.149"
serde_cbor = "0.11.2"
serde_bytes = "0.11.19"

blahaj = "0.6.0"
keyfork-prompt = { version = "0.2.5", registry = "distrust", default-features = false }
keyfork-shard = { version = "0.4.0", registry = "distrust", default-features = false, features = ["openpgp", "openpgp-card"] }
keymaker-models = { version = "0.1.0", path = "../keymaker-models" }

rand = "0.8"
smex = "0.2.0"
bootproof = { git = "https://git.distrust.co/public/bootproof", version = "0.1.0" }
bootproof-sdk = { git = "https://git.distrust.co/public/bootproof", version = "0.1.0" }
x25519-dalek = { version = "2.0.1", features = ["getrandom"] }
hkdf = "0.12.4"
sha2 = "0.10.0"

tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
tokio = { version = "1.50.0", features = ["macros", "net", "rt-multi-thread"] }
keyfork-frame = { version = "0.1.1", registry = "distrust" }
aes-gcm = "0.10.3"
keyforkd = { version = "0.1.5", registry = "distrust", default-features = false, features = ["tracing"] }
daemonize = "0.5.0"
keyfork-mnemonic = { version = "0.4.2", registry = "distrust", default-features = false }
keyfork-derive-openpgp = { version = "0.2.1", registry = "distrust", default-features = false }
keyforkd-client = { version = "0.2.2", registry = "distrust", default-features = false, features = ["ed25519"] }
keyfork-derive-path-data = { version = "0.1.3", registry = "distrust", default-features = false }
ed25519-dalek = "2.2.0"
sequoia-openpgp = "1"
