[package]
name = "keymaker"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
axum = { version = "0.8.8", features = ["macros"] }
dterror = "0.1.0"
keymaker-core = { version = "0.1.0", path = "../keymaker-core", features = ["axum"] }
keymaker-models = { version = "0.1.0", path = "../keymaker-models" }
serde = "1.0.228"
serde_json = "1.0.149"
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = ["rt-multi-thread", "net"] }
tower-http = { version = "0.6.8", features = ["trace"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
zalloc = "0.1.0"

nix = { version = "0.31.2", default-features = false, features = ["reboot"], optional = true }

[dev-dependencies]
reqwest = "0.13.2"

[features]
default = ["selfnuke"]
selfnuke = ["dep:nix"]
